[package]
name = "codi_protocol_common"
version = "0.5.0"
edition = "2021"

[dependencies]
core2 = { version = "0.4.0", default-features = false }

[target.'cfg(any(target_arch = "aarch64", target_arch = "x86_64"))'.dependencies]
serialport = "4.2.1"
