[package]
name = "codi_protocol_common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["serialport"]
stm32 = []

[dependencies]
serialport = { version = "4.2.0", optional = true }
core2 = { version = "0.4.0", default-features = false }
