[package]
name = "codi_protocol_common"
version = "0.3.0"
edition = "2021"

[features]
default = []
std = ["serialport"]
stm32 = []

[dependencies]
serialport = { version = "4.2.1", optional = true }
core2 = { version = "0.4.0", default-features = false }
