[package]
name = "codi_daemon_protocol"
version = "0.6.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72", default-features = false }
thiserror-no-std = "2.0.2"

[dependencies.codi_protocol_common]
path = "../codi_protocol_common"
