[package]
name = "codi_daemon_protocol"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
core2 = "0.4.0"
chrono = "0.4.23"

[dependencies.codi_protocol_common]
path = "../codi_protocol_common"
features = ["std"]
