[package]
name = "codi_daemon_protocol"
version = "0.2.0"
edition = "2021"

[features]
default = ["std"]
stm32 = ["codi_protocol_common/stm32"]
std = ["codi_protocol_common/std"]

[dependencies]
core2 = "0.4.0"

[dependencies.codi_protocol_common]
path = "../codi_protocol_common"
optional = true
