[package]
name = "codi_stock_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = "0.4.0"

[dependencies.codi_proto_common]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
