[package]
name = "codi_os_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = "0.4.0"

[dependencies.prost]
version = "0.11.8"
default-features = false
features = ["prost-derive"]

[dependencies.prost-types]
version = "0.11.8"
default-features = false

[dependencies.codi_protocol_common]
path = "../codi_protocol_common"
default-features = false
features = ["stm32"]

[build-dependencies.prost-build]
version = "0.11.8"
default-features = false
