[package]
name = "codi_proto_common"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["serialport"]
runs-on-stm32 = []

[dependencies]
serialport = { version = "4.2.0", optional = true }
