[package]
name = "codi_proto_common"
version = "0.1.0"
edition = "2018"

[features]
default = ["std"]
std = ["serialport"]
runs-on-stm32 = []

[dependencies]
serialport = { version = "4.0.1", optional = true }
