[package]
name = "codi_boot_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
core2 = { version = "0.4.0", default-features = false }
flatbuffers = "*"

[build-dependencies]
flatc-rust = "*"

[dependencies.codi_protocol_common]
git = "https://github.com/Cosmo-CoDiOS/codi_protocols"
branch = "main"
features = ["stm32"]
default-features = false
