[package]
name = "codi_stock_protocol"
version = "0.2.0"
edition = "2021"

[dependencies]
structure = { git = "https://github.com/Cosmo-CoDiOS/structure", branch = "birkenfeld" }

[dependencies.codi_protocol_common]
path = "../codi_protocol_common"
